# -*- coding: utf-8 -*-
"""image_classification_part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/google/eng-edu/blob/master/ml/pc/exercises/image_classification_part1.ipynb
"""

import numpy as np
from sklearn import datasets
from scipy.spatial import distance_matrix


class hierarchial_clustering:

    def __init__(self, data):

        self.data = data

        self.clusters = list(np.arange(X.shape[0]).reshape((X.shape[0],1)))

    
    def clusters_min_dist(self):

        c = self.clusters
    
        data = self.data
        
        b = []
    
        for c_i in c:
            
            b.append([np.amin(distance_matrix(data[c_i],data[cluster])) for cluster in c])
            
        b = np.array(b)
        
        np.fill_diagonal(b,np.inf)
        
        min_row = b.argmin(axis=0)
        min_col = b.argmin(axis=1)
        
        a=6

iris = datasets.load_iris()
X = iris.data

hc = hierarchial_clustering(X)

a = hc.clusters_min_dist()





